services:
  lerobot:
    image: lerobot:latest
    container_name: lerobot
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/abdelrahman/workspace/panda_mujoco_lerobot:/home/panda_mujoco_lerobot
      - /home/abdelrahman/workspace/mink:/home/mink
      - /home/abdelrahman/workspace/lerobot_mujoco_env:/home/lerobot_mujoco_env

    stdin_open: true 
    tty: true 
    restart: "no"